version: "3.8"

services:
    mongodatabase:
        container_name: mongodb
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "root"
        ports:
            - 27017:27017
        volumes:
            - ./src/database/mongo-data:/data/db